### ISSUE TITLE
Workflow is throwing error

### ISSUE THREAD

**Issue by meitnix** [p4p1/tryhackme-badge-workflow#11]
Hello first of all thanks for the action.
The workflow is throwing the following error:

![image](https://github.com/p4p1/tryhackme-badge-workflow/assets/55987634/2362f784-0d3e-4e62-b42b-39b5db651928)

**Comment by p4p1** [comment]
Hey sorry for the delay I have been supper busy I just checked on the repo should be fixed now :)
