### ISSUE TITLE
Image not displaying

### ISSUE THREAD

**Issue by taylortreece** [p4p1/tryhackme-badge-workflow#3]
Hey p4p1,

Great repo! I'm excited to get it working. I'm having trouble getting the image to display on my profile's read me. 

Here is the .yml file:
![image](https://user-images.githubusercontent.com/67558267/165208669-9878b91f-8599-44ab-9eca-a78b68abaea8.png)

My assets are empty, which I would very well imagine is the reason why, but I'm not exactly sure where to grab the thm badge. Any advice?

Thanks

**Comment by p4p1** [comment]
Sorry for the really late reply I took a break from github for the past 6months ish, if you do not have the asset folder created inside of the repo on github the workflow will have problems uploading the image I believe.
