### ISSUE TITLE
badge image doesn't update

### ISSUE THREAD

**Issue by negin-shahani** [p4p1/tryhackme-badge-workflow#4]
`![tryhackme stats](https://raw.githubusercontent.com/<SET_USERNAME_HERE>/<SET_USERNAME_HERE>/master/assets/thm_propic.png)`
 badge image should update every day, right? the workflow is working but my image is not updating in the assets folder. and I don't know where is my problem. what should I do?

**Comment by p4p1** [comment]
This might be an issue on try hack me side where the static image is not updated as often as the github workflow I have a bit of delay on mine as well I don't really have a fix for that sorry

**Comment by p4p1** [comment]
Quick update I closed it to soon basically you need to regenerate the badge id on the tryhackme side for it to properly update. You can do this by going on your public profile opening the badge selection area and pressing the regenerate badge image button
![image](https://user-images.githubusercontent.com/19672114/181790673-0bfe8c12-ec93-4608-af21-2ffcc2644e24.png)

**Comment by negin-shahani** [comment]
> This might be an issue on try hack me side where the static image is not updated as often as the github workflow I have a bit of delay on mine as well I don't really have a fix for that sorry

oh, thanks for explaining! you really made a great workflow, thank you so much!
